# Generated by Django 3.0.6 on 2020-05-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoatOfArms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_url', models.URLField(verbose_name='Wiki URL')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('image', models.ImageField(upload_to='coas', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_url', models.URLField(verbose_name='Wiki URL')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_url', models.URLField(verbose_name='Wiki URL')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('symbol', models.CharField(max_length=8, verbose_name='Symbol')),
                ('ISO_4217', models.CharField(max_length=8, verbose_name='International Code')),
                ('rate', models.FloatField(verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_url', models.URLField(verbose_name='Wiki URL')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('image', models.ImageField(upload_to='flags', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_url', models.URLField(verbose_name='Wiki URL')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('capital', models.CharField(max_length=128, verbose_name='Capital')),
                ('demonym', models.CharField(max_length=128, verbose_name='Demonym')),
                ('surface', models.BigIntegerField(verbose_name='Surface')),
                ('population', models.BigIntegerField(verbose_name='Population')),
                ('coat_of_arms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.CoatOfArms', verbose_name='Coat of Arms')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Continent', verbose_name='Continent')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Currency', verbose_name='Currency')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Flag', verbose_name='Flag')),
            ],
        ),
    ]
