# Generated by Django 3.0.6 on 2020-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coatofarms',
            name='svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG'),
        ),
        migrations.AddField(
            model_name='flag',
            name='svg',
            field=models.TextField(blank=True, null=True, verbose_name='SVG'),
        ),
    ]
