# Generated by Django 3.0.6 on 2020-05-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200517_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Currency', verbose_name='Currency'),
        ),
    ]
