# Generated by Django 3.0.6 on 2020-05-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200517_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='coat_of_arms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CoatOfArms', verbose_name='Coat of Arms'),
        ),
    ]
